### ISSUE TITLE
Haiku program missing?

### ISSUE THREAD

**Issue by ahope1** [jggames/trs80mc10#2]
Hi. Do you have the listing for the Haiku program? It doesn't seem to run in the online emulator.

http://jimgerrie.blogspot.com/2021/12/lots-of-simple-type-ins.html

**Comment by jggames** [comment]
The source can be found here:

https://github.com/jggames/trs80mc10/tree/master/quicktype/Productivity%20%26%20Education/Haiku

Jim

Sent from Mail for Windows

From: Ant
Sent: Monday, December 6, 2021 12:01 PM
To: jggames/trs80mc10
Cc: Subscribed
Subject: [jggames/trs80mc10] Haiku program missing? (Issue #2)

Hi. Do you have the listing for the Haiku program? It doesn't seem to run in the online emulator.
http://jimgerrie.blogspot.com/2021/12/lots-of-simple-type-ins.html
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lurkio** [comment]
Thanks!

**Comment by ahope1** [comment]
Thanks!
